apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: monitoring
    component: watcher
  name: watcher
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
      component: watcher
  template:
    metadata:
      labels:
        app: monitoring
        component: watcher
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: docker/default
    spec:
      serviceAccountName: monitoring-updater
      tolerations:
      - key: "gravitational.io/runlevel"
        value: system
        operator: Equal
      - key: "gravitational.io/k8s-role"
        operator: "Equal"
        value: "master"
        effect: "NoSchedule"
      containers:
        - name: watcher
          image: watcher:latest
          securityContext:
            runAsUser: 65534
          args:
            - --mode=alerts
