---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-additional-scrape-configs
  namespace: monitoring
type: Opaque
data:
  additional-scrape-configs.yaml: LSBqb2JfbmFtZTogc2F0ZWxsaXRlCiAga3ViZXJuZXRlc19zZF9jb25maWdzOgogICAgLSByb2xlOiBub2RlCiAgc2NoZW1lOiBodHRwCiAgcmVsYWJlbF9jb25maWdzOgogICAgLSBhY3Rpb246IGxhYmVsbWFwCiAgICAgIHJlZ2V4OiBfX21ldGFfa3ViZXJuZXRlc19ub2RlX2xhYmVsXyguKykKICAgIC0gc291cmNlX2xhYmVsczogW19fYWRkcmVzc19fXQogICAgICBhY3Rpb246IHJlcGxhY2UKICAgICAgdGFyZ2V0X2xhYmVsOiBfX2FkZHJlc3NfXwogICAgICByZWdleDogKFteOjtdKyk6KFxkKykKICAgICAgcmVwbGFjZW1lbnQ6ICR7MX06NzU4MAogICAgLSBzb3VyY2VfbGFiZWxzOiBbX19tZXRhX2t1YmVybmV0ZXNfbm9kZV9uYW1lXQogICAgICBhY3Rpb246IHJlcGxhY2UKICAgICAgdGFyZ2V0X2xhYmVsOiBub2RlCiAgICAgIHJlZ2V4OiAoLiopCiAgICAgIHJlcGxhY2VtZW50OiAkezF9CiAgICAjIG1ldHJpY19yZWxhYmVsX2NvbmZpZ3M6CiAgICAjICAgLSByZWdleDogKGt1YmVybmV0ZXNfaW9faG9zdG5hbWV8ZmFpbHVyZV9kb21haW5fYmV0YV9rdWJlcm5ldGVzX2lvX3JlZ2lvbnxiZXRhX2t1YmVybmV0ZXNfaW9fb3N8YmV0YV9rdWJlcm5ldGVzX2lvX2FyY2h8YmV0YV9rdWJlcm5ldGVzX2lvX2luc3RhbmNlX3R5cGV8ZmFpbHVyZV9kb21haW5fYmV0YV9rdWJlcm5ldGVzX2lvX3pvbmUpCiAgICAjICAgICBhY3Rpb246IGxhYmVsZHJvcAo=
