apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0KICBzbXRwX3NtYXJ0aG9zdDogJ2xvY2FsaG9zdDoyNScKcm91dGU6CiAgZ3JvdXBfYnk6IFsnam9iJ10KICBncm91cF93YWl0OiAzMHMKICBncm91cF9pbnRlcnZhbDogNW0KICByZXBlYXRfaW50ZXJ2YWw6IDEyaAogIHJlY2VpdmVyOiAnbnVsbCcKICByb3V0ZXM6CiAgICAtIG1hdGNoOgogICAgICAgIGFsZXJ0bmFtZTogV2F0Y2hkb2cKICAgICAgICByZWNlaXZlcjogJ251bGwnCnJlY2VpdmVyczoKICAtIG5hbWU6ICdudWxsJwo=
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
