apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0Kcm91dGU6CiAgZ3JvdXBfYnk6IFsnam9iJ10KICBncm91cF93YWl0OiAzMHMKICBncm91cF9pbnRlcnZhbDogNW0KICByZXBlYXRfaW50ZXJ2YWw6IDEyaAogIHJlY2VpdmVyOiAnbnVsbCcKICByb3V0ZXM6CiAgICAtIG1hdGNoOgogICAgICAgIGFsZXJ0bmFtZTogV2F0Y2hkb2cKICAgICAgICByZWNlaXZlcjogJ251bGwnCnJlY2VpdmVyczoKICAtIG5hbWU6ICdudWxsJwogIC0gbmFtZTogJ1Rlc3QnCiAgICBlbWFpbF9jb25maWdzOgogICAgICAtIHRvOiAnc2VyZ2VpQGdyYXZpdGF0aW9uYWwuY29tJwo=
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
