apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0KICBzbXRwX3NtYXJ0aG9zdDogJ2xvY2FsaG9zdDoyNScKICBzbXRwX2Zyb206ICdub3JlcGx5QHBsYXRmb3JtLmdyYXZpdGF0aW9uYWwuaW8nCiAgc210cF9yZXF1aXJlX3RsczogZmFsc2UKcm91dGU6CiAgZ3JvdXBfYnk6IFsnam9iJ10KICBncm91cF93YWl0OiAzMHMKICBncm91cF9pbnRlcnZhbDogNW0KICByZXBlYXRfaW50ZXJ2YWw6IDEyaAogIHJlY2VpdmVyOiAnZGVmYXVsdCcKICByb3V0ZXM6CiAgICAtIG1hdGNoOgogICAgICAgIGFsZXJ0bmFtZTogV2F0Y2hkb2cKICAgICAgICByZWNlaXZlcjogJ2JsYWNraG9sZScKcmVjZWl2ZXJzOgogIC0gbmFtZTogJ2RlZmF1bHQnCiAgLSBuYW1lOiAnYmxhY2tob2xlJwo=
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
