apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-state-metrics
  name: kube-state-metrics
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: https-main
    port: 8443
    targetPort: https-main
  - name: https-telemetry
    port: 9443
    targetPort: https-telemetry
  selector:
    app: monitoring
    component: kube-state-metrics
